apply plugin: 'com.android.application'

android {
    namespace "rustamspl.github.io.startchat"
    compileSdkVersion 36
    defaultConfig {
        applicationId "rustamspl.github.io.startchat"
        minSdkVersion 29
        targetSdkVersion 36
        versionCode 8
        versionName "1.3.4"
    }
    buildTypes {
        release {
            minifyEnabled true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
